#
# Module manifest for module 'SimpleTicket'
#
# Generated by: Philip Aaron Daughtry
#
# Generated on: 1/18/2025
#

@{
	RootModule = 'SimpleTicket.psm1'
	ModuleVersion = '1.0.0'
	Author = 'Philip Aaron Daughtry'
	Copyright = '(c) 2025 Philip Aaron Daughtry. All rights reserved.'
	Description = 'A terminal-based PowerShell module for taking, searching through, and managing ticket-based notes.'
	PowerShellVersion = '5.1'
	FunctionsToExport = '*'
	CmdletsToExport = '*'
	VariablesToExport = '*'
	AliasesToExport = '*'
}
